// Generated by gencpp from file mobot_pub_des_state/integer_queryRequest.msg
// DO NOT EDIT!


#ifndef MOBOT_PUB_DES_STATE_MESSAGE_INTEGER_QUERYREQUEST_H
#define MOBOT_PUB_DES_STATE_MESSAGE_INTEGER_QUERYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobot_pub_des_state
{
template <class ContainerAllocator>
struct integer_queryRequest_
{
  typedef integer_queryRequest_<ContainerAllocator> Type;

  integer_queryRequest_()
    {
    }
  integer_queryRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct integer_queryRequest_

typedef ::mobot_pub_des_state::integer_queryRequest_<std::allocator<void> > integer_queryRequest;

typedef boost::shared_ptr< ::mobot_pub_des_state::integer_queryRequest > integer_queryRequestPtr;
typedef boost::shared_ptr< ::mobot_pub_des_state::integer_queryRequest const> integer_queryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace mobot_pub_des_state

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobot_pub_des_state/integer_queryRequest";
  }

  static const char* value(const ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#empty \n"
;
  }

  static const char* value(const ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct integer_queryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mobot_pub_des_state::integer_queryRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MOBOT_PUB_DES_STATE_MESSAGE_INTEGER_QUERYREQUEST_H
