// Generated by gencpp from file mobot_pub_des_state/integer_query.msg
// DO NOT EDIT!


#ifndef MOBOT_PUB_DES_STATE_MESSAGE_INTEGER_QUERY_H
#define MOBOT_PUB_DES_STATE_MESSAGE_INTEGER_QUERY_H

#include <ros/service_traits.h>


#include <mobot_pub_des_state/integer_queryRequest.h>
#include <mobot_pub_des_state/integer_queryResponse.h>


namespace mobot_pub_des_state
{

struct integer_query
{

typedef integer_queryRequest Request;
typedef integer_queryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct integer_query
} // namespace mobot_pub_des_state


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mobot_pub_des_state::integer_query > {
  static const char* value()
  {
    return "648675cba6b3813e536ad7dad105da98";
  }

  static const char* value(const ::mobot_pub_des_state::integer_query&) { return value(); }
};

template<>
struct DataType< ::mobot_pub_des_state::integer_query > {
  static const char* value()
  {
    return "mobot_pub_des_state/integer_query";
  }

  static const char* value(const ::mobot_pub_des_state::integer_query&) { return value(); }
};


// service_traits::MD5Sum< ::mobot_pub_des_state::integer_queryRequest> should match
// service_traits::MD5Sum< ::mobot_pub_des_state::integer_query >
template<>
struct MD5Sum< ::mobot_pub_des_state::integer_queryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mobot_pub_des_state::integer_query >::value();
  }
  static const char* value(const ::mobot_pub_des_state::integer_queryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mobot_pub_des_state::integer_queryRequest> should match
// service_traits::DataType< ::mobot_pub_des_state::integer_query >
template<>
struct DataType< ::mobot_pub_des_state::integer_queryRequest>
{
  static const char* value()
  {
    return DataType< ::mobot_pub_des_state::integer_query >::value();
  }
  static const char* value(const ::mobot_pub_des_state::integer_queryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mobot_pub_des_state::integer_queryResponse> should match
// service_traits::MD5Sum< ::mobot_pub_des_state::integer_query >
template<>
struct MD5Sum< ::mobot_pub_des_state::integer_queryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mobot_pub_des_state::integer_query >::value();
  }
  static const char* value(const ::mobot_pub_des_state::integer_queryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mobot_pub_des_state::integer_queryResponse> should match
// service_traits::DataType< ::mobot_pub_des_state::integer_query >
template<>
struct DataType< ::mobot_pub_des_state::integer_queryResponse>
{
  static const char* value()
  {
    return DataType< ::mobot_pub_des_state::integer_query >::value();
  }
  static const char* value(const ::mobot_pub_des_state::integer_queryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOBOT_PUB_DES_STATE_MESSAGE_INTEGER_QUERY_H
